spring:
  application:
    name: zzinterior

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://mySqlTest:3306/dbTest?useSSL=false&allowPublicKeyRetrieval=true
    url: jdbc:mysql://localhost:3306/dbTest
    username : ${DB_PASSWORD:root}
    password : ${DB_USERNAME:root}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
#            redirect-uri: http://localhost:8080/login/oauth2/code/google
#            redirect-uri: http://localhost:8080/api/auth/google
            redirect-uri: http://localhost:3000
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
jwt:
  key: ${JWT_SECRET_KEY}